### ISSUE TITLE
Body Descriptors are duplicated when installing a new asset pack

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#110]
Hi Piranha, here's another bug. When installing a new asset pack which includes annotated body descriptors, synthebd is always creating new entries for them, even if they already exist. Installing 2 or 3 asset packs in a row results in having 2-3 sets of duplicated bodyslide descriptors.

**Comment by Piranha91** [comment]
Awesome, thanks for reporting this. I’ve noticed once in a while that I end up with duplicate descriptors but I never tracked down when and how they appear. Thanks for letting me know.

**Comment by Piranha91** [comment]
Should be fixed in 0.9.7.3. Thanks again for pinpointing this; it's been an issue that's irritated me for months but because I've only had sporadic time to work on this and other issues have taken priority I never had the time to figure out what triggered it.

**Comment by leonardovcr** [comment]
Looks like it is fixed now, thanks! 

Howver, I've noticed something, that I don't know if it is intended behaviour or not. I think it's another bug...

When installing a new asset pack with 'apply body shapes using' set to 'none' on 'general settings tab', the installer imports the body descriptors but ignores all body shape descriptors annotated on the asset pack's body normal subgroups 🤔. I've just checked the installed asset pack .json, and there are no bodyslide descriptors there, even though they do exist on the original .json of the archive.

**Comment by Piranha91** [comment]
Do you mean the allowed/disallowed descriptors? If so, I can't replicate - I just tried installing my Tempered Skins config file with body shape distribution set to none, and when I saved the config file the descriptors were still there in the .json and visible when I set the body shape distribution to BodySlide. Which config file are you seeing this for?

**Comment by leonardovcr** [comment]
Yeah, allowed/disallowed descriptors. 

Sry, I didn't check the .json properly :( I found the descriptors there now. However, they still don't appear on the UI:

![image](https://user-images.githubusercontent.com/13605450/223007476-aaed6223-8c43-4a48-a257-b7b910ca433b.png)

Here's how I'm able to reproduce:
 - Unzipped and launched the new 0.9.7.3 version
 - Imported this custom bodyslde (https://www.nexusmods.com/skyrimspecialedition/mods/73717?tab=files&file_id=362676). It took a while.
 - Installed your latest Tempered Skins for Female CBBE. Installation took many minutes... very strange.
 - Set Bodyslides via OBody on general settings in order to view the Allowed/Disallowed descriptors on the Tex Mesh UI.
 - Tried restarting SynthEBD, and still no descriptors on UI.

Strange...

**Comment by leonardovcr** [comment]
Hah, now that I closed the app, the descriptors are gone from the .json 🤣  So that's why I couldn't find them before. I checked the file while installation was running, and it had the descriptors there. After closing the app, the file was saved just as it was on the UI, without descriptors!

**Comment by Piranha91** [comment]
Did you install the version with MCSmarties BodyGen? I noticed yesterday that the one without MCSmarties actually doesn’t have annotated bodyslide descriptors - will need to fix that before release.

Installation taking a long time is due to the UI being generated for the config file - still trying to figure out how to cut down on that.

**Comment by leonardovcr** [comment]
Oh I chose the version without MCSmarties BodyGen. Will test again choosing it then.

**Comment by leonardovcr** [comment]
Yeah, the problem was not choosing the MCSmarties BodyGen during installation. Now the descriptor annotations are correctly installed... didn't know there were two different confs on the archive. Anyway, I think we can close this issue now :)
